package permissions.dispatcher.processor.util;

/**
 * Created by Lilei on 2016.
 */

public interface Constants {

    String FILE_COMMENT = "This file was generated by PermissionsDispatcher. Do not modify!";
    String GEN_CLASS_SUFFIX = "PermissionsDispatcher";
    String GEN_REQUESTCODE_PREFIX = "REQUEST_";
    String GEN_PERMISSION_PREFIX = "PERMISSION_";
    String GEN_PENDING_PREFIX = "PENDING_";
    String GEN_WITHCHECK_SUFFIX = "WithCheck";
    String GEN_PERMISSIONREQUEST_SUFFIX = "PermissionRequest";
}
